apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: test-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.my_server: rajesh.sangepu@opsmx.io
    notifications.argoproj.io/subscribe.on-sync-failed.my_server: rajesh.sangepu@opsmx.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Rajesh-Sangepu/youtube.git'
    path: argocd/notifications/manifests/app
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
